name: Apollo aire build

on:
  push:
    branches: [ feature/cicd ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Change folder
      run: cd Firmware/aire_apollo/
    # - name: configure
    #   run: ./configure
    - name: make
      run: Firmware/aire_apollo/make
    - name: make check
      run: Firmware/aire_apollo/make check
    - name: make distcheck
      run: Firmware/aire_apollo/make distcheck
